/**
 * EventCatalog configuration.
 *
 * Note: EventCatalog v4 loads this file as an ES module, so it uses
 * `export default` (not `module.exports`), even though the file ends in .js.
 *
 * The catalog CONTENT (domains, services, events) is not configured here -
 * it is generated by `npm run sync` from ../catalog-data/architecture.json.
 */

/** @type {import('@eventcatalog/core/bin/eventcatalog.config').Config} */
export default {
  cId: '9f2a6d41-0c3b-4a77-9b0e-000000000001',
  title: 'ITS RMS Event Catalog (POC)',
  tagline:
    'Medical camp domains, services and events. Proof of concept only - all sample data is fictional.',
  organizationName: 'ITS RMS - Proof of Concept',
  homepageLink: 'https://eventcatalog.dev',
  landingPage: '',
  editUrl: '',
  port: 3000,
  base: '/',
  trailingSlash: false,
  // Static build: `npm run build` writes ./dist, `npm run preview` serves it.
  output: 'static',
  logo: {
    alt: 'ITS RMS POC',
    text: 'ITS RMS POC',
  },
  generators: [],
};
